### ISSUE TITLE
Call homing once on_configured is called and remove unnecessary `file` write

### ISSUE THREAD

**Issue by 5730289021-NN** [FIBO-Engineer/ros2_keya_driver#14]
Remove

https://github.com/FIBO-Engineer/ros2_keya_driver/blob/7481c7737a9958a1aad853a047b8c8f6a880c503/src/keya_driver_hw.cpp#L580-L597

**Comment by nsujumnong** [comment]
homing is now implemented in "on_activate" function and will be activated upon waking up. It's no longer called via ros publish
